# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/intel_project/AX7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0.xci
# IP: The module: 'system_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/intel_project/AX7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/intel_project/AX7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/intel_project/AX7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/intel_project/AX7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0.xci
# IP: The module: 'system_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/intel_project/AX7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/intel_project/AX7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/intel_project/AX7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_0/system_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
