# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ax7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_3/system_axis_subset_converter_0_3.xci
# IP: The module: 'system_axis_subset_converter_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ax7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_3/system_axis_subset_converter_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_subset_converter_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/ax7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_3/system_axis_subset_converter_0_3.xci
# IP: The module: 'system_axis_subset_converter_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ax7010/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_3/system_axis_subset_converter_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_subset_converter_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
