# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ax7010MODIFY/AX7010_MODIFY/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_m00_regslice_1/system_m00_regslice_1.xci
# IP: The module: 'system_m00_regslice_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ax7010MODIFY/AX7010_MODIFY/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_m00_regslice_1/system_m00_regslice_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_m00_regslice_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/ax7010MODIFY/AX7010_MODIFY/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_m00_regslice_1/system_m00_regslice_1.xci
# IP: The module: 'system_m00_regslice_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ax7010MODIFY/AX7010_MODIFY/16_ov5640_dual/ov5640_dual.srcs/sources_1/bd/system/ip/system_m00_regslice_1/system_m00_regslice_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_m00_regslice_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
